import pandas as pd

configfile: "config/config.yaml"

samples = (
    pd.read_csv(config["samples"], sep="\t", comment="#")
    .set_index("sample", drop=False)
)
SAMPLES = samples.index.tolist()


rule all:
    input:
        expand("results/salmon/{s}/quant.sf", s=SAMPLES),
        "results/qc/multiqc_report.html",


rule fastqc_raw:
    input:
        r1="data/raw/{s}_R1.fastq.gz",
        r2="data/raw/{s}_R2.fastq.gz",
    output:
        "results/qc/fastqc/{s}_R1_fastqc.zip",
        "results/qc/fastqc/{s}_R2_fastqc.zip",
    threads: 2
    log: "logs/fastqc/{s}.log"
    shell:
        "fastqc -t {threads} -o results/qc/fastqc {input.r1} {input.r2} &> {log}"


rule fastp:
    input:
        r1="data/raw/{s}_R1.fastq.gz",
        r2="data/raw/{s}_R2.fastq.gz",
    output:
        r1="results/trimmed/{s}_R1.fastq.gz",
        r2="results/trimmed/{s}_R2.fastq.gz",
        json="results/qc/fastp/{s}.fastp.json",
        html="results/qc/fastp/{s}.fastp.html",
    threads: 4
    log: "logs/fastp/{s}.log"
    shell:
        "fastp -i {input.r1} -I {input.r2} -o {output.r1} -O {output.r2} "
        "--detect_adapter_for_pe -w {threads} "
        "-j {output.json} -h {output.html} &> {log}"


rule salmon_index:
    input:
        config["transcriptome"],
    output:
        directory("resources/salmon_index"),
    threads: 8
    resources:
        mem_mb=32000,
        runtime=120,
    log: "logs/salmon_index.log"
    shell:
        "salmon index -t {input} -i {output} -k 31 -p {threads} &> {log}"


rule salmon_quant:
    input:
        idx="resources/salmon_index",
        r1="results/trimmed/{s}_R1.fastq.gz",
        r2="results/trimmed/{s}_R2.fastq.gz",
    output:
        "results/salmon/{s}/quant.sf",
    params:
        outdir="results/salmon/{s}",
    threads: 8
    resources:
        mem_mb=16000,
        runtime=60,
    log: "logs/salmon/{s}.log"
    shell:
        "salmon quant -i {input.idx} -l A -1 {input.r1} -2 {input.r2} "
        "--validateMappings --gcBias -p {threads} -o {params.outdir} &> {log}"


rule multiqc:
    input:
        expand("results/qc/fastqc/{s}_R1_fastqc.zip", s=SAMPLES),
        expand("results/qc/fastp/{s}.fastp.json", s=SAMPLES),
        expand("results/salmon/{s}/quant.sf", s=SAMPLES),
    output:
        "results/qc/multiqc_report.html",
    log: "logs/multiqc.log"
    shell:
        "multiqc results/qc results/salmon -o results/qc -f &> {log}"
